const KEY='julius-vagter-v1', RATEKEY='julius-vagter-rate';
let shifts=JSON.parse(localStorage.getItem(KEY)||'[]'); let rate=Number(localStorage.getItem(RATEKEY)||80); let tab='home'; let editId=null;
const pad=n=>String(n).padStart(2,'0');
function localISO(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseDate(s){let [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function periodFor(date){let d=new Date(date), endMonth=d.getDate()>=20?d.getMonth()+1:d.getMonth(), endYear=d.getFullYear(); if(endMonth>11){endMonth=0;endYear++} let startMonth=endMonth-1,startYear=endYear;if(startMonth<0){startMonth=11;startYear--}return {start:new Date(startYear,startMonth,20),end:new Date(endYear,endMonth,19),key:`${endYear}-${pad(endMonth+1)}`,name:new Intl.DateTimeFormat('da-DK',{month:'long',year:'numeric'}).format(new Date(endYear,endMonth,1))}}
function minutes(s){let [h,m]=s.split(':').map(Number);return h*60+m}
function workMinutes(x){let n=minutes(x.end)-minutes(x.start)-Number(x.break||0);if(n<0)n+=1440;return Math.max(0,n)}
function money(n){return new Intl.NumberFormat('da-DK',{style:'currency',currency:'DKK',minimumFractionDigits:2}).format(n)}
function duration(m){return `${Math.floor(m/60)} t ${m%60} min`}
function fmtDate(s){return new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short',year:'numeric'}).format(parseDate(s))}
function save(){localStorage.setItem(KEY,JSON.stringify(shifts));localStorage.setItem(RATEKEY,String(rate))}
function currentPeriod(){return periodFor(new Date())}
function inPeriod(x,p){let d=parseDate(x.date);return d>=p.start&&d<=p.end}
function summary(list){let mins=list.reduce((a,x)=>a+workMinutes(x),0);return {mins,pay:mins/60*rate}}
function shell(content){return `<main class="app">${content}</main><nav class="tabs"><div class="tabs-inner">${[['home','⌂','Overblik'],['shifts','☷','Vagter'],['settings','⚙︎','Indstillinger']].map(([t,i,l])=>`<div class="tab ${tab===t?'active':''}" onclick="go('${t}')"><span>${i}</span>${l}</div>`).join('')}</div></nav>`}
function home(){let p=currentPeriod(),list=shifts.filter(x=>inPeriod(x,p)),s=summary(list);return shell(`<h1>Julius Vagter</h1><div class="card"><div class="muted">Denne lønperiode</div><div class="hours">${fmtDate(localISO(p.start))} – ${fmtDate(localISO(p.end))}</div><div class="money">${money(s.pay)}</div><div class="muted">${duration(s.mins)} · ${list.length} ${list.length===1?'vagt':'vagter'}</div></div><button class="btn" onclick="showShiftForm()">＋ Registrer vagt</button><div class="card"><strong>Seneste vagter</strong>${shifts.length?shifts.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(shiftHTML).join(''):'<div class="empty">Ingen vagter registreret endnu.</div>'}</div>`)}
function shiftHTML(x){let m=workMinutes(x);return `<div class="shift"><div class="row"><div><strong>${fmtDate(x.date)}</strong><span class="muted">${x.start}–${x.end} · ${x.break} min pause</span></div><div style="text-align:right"><strong>${money(m/60*rate)}</strong><span class="muted">${duration(m)}</span></div></div><div class="actions"><button class="mini edit" onclick="showShiftForm('${x.id}')">Rediger</button><button class="mini delete" onclick="del('${x.id}')">Slet</button></div></div>`}
function periods(){let ps=[...new Map(shifts.map(x=>{let p=periodFor(parseDate(x.date));return [p.key,p]})).values()].sort((a,b)=>b.key.localeCompare(a.key));let selected=window.selectedPeriod||currentPeriod().key;if(!ps.some(p=>p.key===selected))ps.unshift(currentPeriod());let p=ps.find(p=>p.key===selected)||ps[0],list=shifts.filter(x=>inPeriod(x,p)).sort((a,b)=>b.date.localeCompare(a.date)),s=summary(list);return shell(`<h1>Vagter</h1><select class="period-select" onchange="window.selectedPeriod=this.value;render()">${ps.map(q=>`<option value="${q.key}" ${q.key===p.key?'selected':''}>${q.name[0].toUpperCase()+q.name.slice(1)} · ${fmtDate(localISO(q.start))} – ${fmtDate(localISO(q.end))}</option>`).join('')}</select><div class="summary-grid"><div class="small-card"><span class="muted">Arbejdstid</span><b>${duration(s.mins)}</b></div><div class="small-card"><span class="muted">Forventet løn</span><b>${money(s.pay)}</b></div></div><div class="card">${list.length?list.map(shiftHTML).join(''):'<div class="empty">Ingen vagter i denne lønperiode.</div>'}</div><button class="btn" onclick="showShiftForm()">＋ Registrer vagt</button>`)}
function settings(){return shell(`<h1>Indstillinger</h1><div class="card"><label>Timeløn (kr.)</label><input id="rate" type="number" inputmode="decimal" step="0.5" value="${rate}"><button class="btn" onclick="setRate()">Gem timeløn</button><p class="muted">Lønnen er et estimat: arbejdstid efter pause × timeløn. Lønperioder går automatisk fra den 20. til den 19.</p></div><div class="card"><strong>Data</strong><p class="muted">Vagterne gemmes kun på denne enhed i browserens lokale lager. Sletter man webstedsdata, kan registreringerne forsvinde.</p></div>`)}
function showShiftForm(id){editId=id||null;let x=shifts.find(s=>s.id===id)||{date:localISO(new Date()),start:'16:00',end:'20:00',break:0};document.getElementById('app').innerHTML=`<main class="app"><h1>${id?'Rediger vagt':'Registrer vagt'}</h1><div class="card"><label>Dato</label><input id="date" type="date" value="${x.date}"><label>Mødetid</label><input id="start" type="time" value="${x.start}"><label>Sluttid</label><input id="end" type="time" value="${x.end}"><label>Pause (minutter)</label><input id="break" type="number" inputmode="numeric" min="0" step="1" value="${x.break}"></div><button class="btn" onclick="submitShift()">Gem vagt</button><button class="btn secondary" onclick="render()">Annuller</button></main>`}
function submitShift(){let x={id:editId||String(Date.now()),date:document.getElementById('date').value,start:document.getElementById('start').value,end:document.getElementById('end').value,break:Number(document.getElementById('break').value||0)};if(!x.date||!x.start||!x.end)return alert('Udfyld dato, mødetid og sluttid.');let i=shifts.findIndex(s=>s.id===x.id);if(i>=0)shifts[i]=x;else shifts.push(x);save();tab='home';render()}
function del(id){if(confirm('Vil du slette denne vagt?')){shifts=shifts.filter(x=>x.id!==id);save();render()}}
function setRate(){rate=Number(document.getElementById('rate').value)||80;save();render()}
function go(t){tab=t;render()}
function render(){document.getElementById('app').innerHTML=tab==='home'?home():tab==='shifts'?periods():settings()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
